version: '3.8'

services:
  app:
    image: cicd-aws:latest
    container_name: cicd-aws-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
    restart: always