name: Docker Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Spring Boot App
        run: ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t cicd-aws:latest .

      - name: Save Docker image as tar
        run: docker save cicd-aws:latest -o app-image.tar

      - name: List root files
        run: ls -al

      - name: Copy Docker image and compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: |
            app-image.tar
            docker-compose.yml
          target: ~/deploy

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/deploy
            docker load -i app-image.tar
            docker compose down || true
            docker compose up -d